{% set name = "conda-forge-feedstock-ops" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-forge-feedstock-ops/archive/refs/tags/{{ version }}.tar.gz
  sha256: ccc73122dc2a600cddb804de2a08f0c3b98e1d6f6be359179bb5b0393e17011a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - conda-forge-feedstock-ops-container = conda_forge_feedstock_ops.__main__:main_container

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.11
    - click
    - conda-build >=3.27
    - conda-smithy >=3.40.1
    - python-rapidjson
    - pyyaml
    - rattler-build-conda-compat >=0.0.2,<2.0.0a0
    - python-rapidjson

test:
  imports:
    - conda_forge_feedstock_ops
  requires:
    - pip
  commands:
    - pip check
    - python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ == '{{ version }}'"
    - conda-forge-feedstock-ops-container --help

about:
  home: https://github.com/regro/conda-forge-feedstock-ops
  summary: 'A package of containerized feedstock maintenance operations'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
