{% set name = "conda-forge-feedstock-ops" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-forge-feedstock-ops/archive/refs/tags/{{ version }}.tar.gz
  sha256: c5a2ef4d28a01dda2387c990863f94b8e321e254e33923716a626871be26985f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - conda-forge-feedstock-ops-container = conda_forge_feedstock_ops.__main__:main_container

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.11
    - python-rapidjson
    - requests
    - ruamel.yaml
    - click
    - conda
    - conda-package-handling
    - conda-smithy
    - conda-build
    - libmambapy >=1.5.1,<2.0a0
    - ruamel.yaml.jinja2
    - conda-forge-metadata >=0.2.0
    - wurlitzer
    - requests
    - zstandard
    - boltons >=23.0.0
    - py-rattler >=0.6.2,<0.7a0

test:
  imports:
    - conda_forge_feedstock_ops
  requires:
    - pip
  commands:
    - pip check
    - python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ == '{{ version }}'"
    - conda-forge-feedstock-ops-container --help

about:
  home: https://github.com/regro/conda-forge-feedstock-ops
  summary: 'A package of containerized feedstock maintenance operations'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
